// <auto-generated />
using System;
using FinancialOS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialOS.Data.Migrations
{
    [DbContext(typeof(FinancialOsDbContext))]
    partial class FinancialOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FinancialOS.Core.Models.CanonicalMerchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedKey")
                        .IsUnique()
                        .HasDatabaseName("IX_CanonicalMerchant_NormalizedKey_Unique");

                    b.ToTable("CanonicalMerchants");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_Name_Unique");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.ClassificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScopeReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetMerchantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ClassificationRule_Name_Unique");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_ClassificationRule_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ClassificationRule_Status");

                    b.ToTable("ClassificationRules");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.DuplicateCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateGroupKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchedRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateGroupKey")
                        .HasDatabaseName("IX_DuplicateCandidate_GroupKey");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DuplicateCandidate_Status");

                    b.ToTable("DuplicateCandidates");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FinancialAccount_Name");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sha256Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_FinancialEvidence_Sha256Hash_Unique");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_FinancialEvidence_UploadedAt");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_FinancialRecord_AccountId");

                    b.HasIndex("EvidenceId")
                        .HasDatabaseName("IX_FinancialRecord_EvidenceId");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_FinancialRecord_OccurredOn");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FinancialRecord_Status");

                    b.HasIndex("AccountId", "Status")
                        .HasDatabaseName("IX_FinancialRecord_AccountId_Status");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Merchant_Name");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.MerchantAliasMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasNormalizedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasRawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalMerchantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceWeight")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MerchantAlias_IsActive");

                    b.HasIndex("CanonicalMerchantId", "AliasNormalizedText")
                        .HasDatabaseName("IX_MerchantAlias_Canonical_AliasNormalized");

                    b.ToTable("MerchantAliases");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.NormalizationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanonicalMerchantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinancialRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersededByDecisionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_NormalizationDecision_CreatedAtUtc");

                    b.HasIndex("FinancialRecordId")
                        .HasDatabaseName("IX_NormalizationDecision_RecordId");

                    b.ToTable("NormalizationDecisions");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.PlanningScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedRecordIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PlanningScenario_CreatedAt");

                    b.ToTable("PlanningScenarios");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.ProvenanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinancialRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StepSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ProvenanceEntry_CorrelationId");

                    b.HasIndex("FinancialRecordId", "StepSequence")
                        .IsUnique()
                        .HasDatabaseName("IX_ProvenanceEntry_Record_StepSequence_Unique");

                    b.ToTable("ProvenanceEntries");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Rule_Name_Unique");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialRecord", b =>
                {
                    b.OwnsOne("FinancialOS.Core.Models.Confidence", "ClassificationConfidence", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Score")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClassificationConfidence");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("Records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.OwnsOne("FinancialOS.Core.Models.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("Records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.OwnsOne("FinancialOS.Core.Models.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlgorithmVersion")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvenanceAlgorithmVersion");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvenanceRuleName");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvenanceSource");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("Records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("ClassificationConfidence");

                    b.Navigation("Provenance");
                });
#pragma warning restore 612, 618
        }
    }
}
