// <auto-generated />
using System;
using FinancialOS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialOS.Data.Migrations
{
    [DbContext(typeof(FinancialOsDbContext))]
    partial class FinancialOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FinancialOS.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.PlanningScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedRecordIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanningScenarios");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("FinancialOS.Core.Models.FinancialRecord", b =>
                {
                    b.OwnsOne("FinancialOS.Core.Models.Confidence", "ClassificationConfidence", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Score")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClassificationConfidence");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("Records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.OwnsOne("FinancialOS.Core.Models.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("Records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.OwnsOne("FinancialOS.Core.Models.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AlgorithmVersion")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvenanceAlgorithmVersion");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvenanceRuleName");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvenanceSource");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("Records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("ClassificationConfidence");

                    b.Navigation("Provenance");
                });
#pragma warning restore 612, 618
        }
    }
}
