<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinancialOS.Core\FinancialOS.Core.csproj" />
    <ProjectReference Include="..\FinancialOS.Data\FinancialOS.Data.csproj" />
    <ProjectReference Include="..\FinancialOS.Shared\FinancialOS.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
